// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Com_button: typeof import('./src/components/common_cpn/com_button.vue')['default']
    Csj: typeof import('./src/components/Uncommon/csj.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    HomeView: typeof import('./src/components/View/HomeView.vue')['default']
    LoginView: typeof import('./src/components/View/loginView.vue')['default']
    'LoginView copy': typeof import('./src/components/loginView copy.vue')['default']
    'LoginView copy 2': typeof import('./src/components/View/loginView copy 2.vue')['default']
    Order: typeof import('./src/components/Uncommon/Order.vue')['default']
    PermissionModification: typeof import('./src/components/Uncommon/PermissionModification.vue')['default']
    Personal: typeof import('./src/components/View/personal.vue')['default']
    ProductList: typeof import('./src/components/Uncommon/ProductList.vue')['default']
    Role: typeof import('./src/components/View/role.vue')['default']
    RoleView: typeof import('./src/components/View/roleView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snake: typeof import('./src/components/Uncommon/Snake.vue')['default']
    UpdataP: typeof import('./src/components/Uncommon/updataP.vue')['default']
    User: typeof import('./src/components/Uncommon/User.vue')['default']
  }
}

export {}
